name = './/fieldset[1]//input'
email = './/fieldset[2]//input'
password = './/fieldset[3]//input'
registration_button = './/button[text()="Зарегистрироваться"]'
password_error = './/fieldset[3]//p'
login_button_main = './/button[text()="Войти"]'
login_button_side = '[href="/login"]'
lk_button = '[href="/account"]'
main_paragraph = './/section/h1[text()="Соберите бургер"]' #Заголовок конструктора
sauces_tab = './/span[text()="Соусы"]'
fillings_tab = './/span[text()="Начинки"]'
constructor_button = './/li[1]//p[@class="AppHeader_header__linkText__3q_va ml-2"]'
logo = ".//div/a[@href='/']"
logout_button = './/li/button'
login_into_account_button = './/button[@class="button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg"]'
buns_main_tab = './/section/div/div[1][@class="tab_tab__1SPyG tab_tab_type_current__2BEPc pt-4 pr-10 pb-4 pl-10 noselect"]'
sauces_main_tab = './/section/div/div[2][@class="tab_tab__1SPyG tab_tab_type_current__2BEPc pt-4 pr-10 pb-4 pl-10 noselect"]'
fillings_main_tab = './/section/div/div[3][@class="tab_tab__1SPyG tab_tab_type_current__2BEPc pt-4 pr-10 pb-4 pl-10 noselect"]'
lk_text = './/p[@class="Account_text__fZAIn text text_type_main-default"]' #"В этом разделе вы можете изменить свои персональные данные"
main_url = 'https://stellarburgers.nomoreparties.site/'
registration_url = 'https://stellarburgers.nomoreparties.site/register'
login_url = 'https://stellarburgers.nomoreparties.site/login'
lk_url = 'https://stellarburgers.nomoreparties.site/account/profile'
forgot_password_url = 'https://stellarburgers.nomoreparties.site/forgot-password'
